services:
  - type: web
    name: thez-solutions
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
