"""remove submission_date

Revision ID: 6ab3a2ed570e
Revises: 
Create Date: 2025-01-09 02:48:39.288622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab3a2ed570e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_requests')
    op.drop_table('project_request_files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_request_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_request_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_request_id'], ['project_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('project_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('features', sa.TEXT(), nullable=False),
    sa.Column('timeline', sa.VARCHAR(length=20), nullable=False),
    sa.Column('budget_range', sa.VARCHAR(length=20), nullable=False),
    sa.Column('contact_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('contact_phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('preferred_contact', sa.VARCHAR(length=10), nullable=False),
    sa.Column('additional_info', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('submission_date', sa.DATETIME(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
