"""Add project documents

Revision ID: 8c133f6ff5a0
Revises: 0c29d647c383
Create Date: 2024-12-21 05:15:20.415772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c133f6ff5a0'
down_revision = '0c29d647c383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status_updated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['status_updated_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status_updated_by')
        batch_op.drop_column('status_updated_at')

    # ### end Alembic commands ###
